### ISSUE TITLE
Install Qsessions

### ISSUE THREAD

**Issue by YazdanRa** [QueraTeam/django-qsessions#13]
I received this error when I want to build docker-compose through the command `docker-compose build`:

```terminal
Collecting django-qsessions==1.1.0 (from -r /root/requirements.txt (line 18))
  Downloading https://files.pythonhosted.org/packages/5d/d1/198912d3740a6ffe9820ad229c239e3f4ef912e4b4baaf7d261f027a22eb/django-qsessions-1.1.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-xnld3yme/django-qsessions/setup.py", line 5, in <module>
        README = readme.read()
      File "/usr/lib/python3.6/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 1423: ordinal not in range(128)
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-xnld3yme/django-qsessions/
ERROR: Service 'web' failed to build: The command '/bin/sh -c pip install -r /root/requirements.txt' returned a non-zero code: 1                                                                            
```
 Is there any solution for this issue?!

[Possible solution](https://stackoverflow.com/questions/18649512/unicodedecodeerror-ascii-codec-cant-decode-byte-0xe2-in-position-13-ordinal)

**Comment by YazdanRa** [comment]
Thank you 🙌🏼
